version: '3.8'

services:
  backend:
    build:
      context: ./app-backend
    container_name: secureshift-backend
    ports:
      - "5000:5000"
    env_file:
      - ./app-backend/.env
    depends_on:
      - mongodb
    restart: unless-stopped
    networks:
      - secureshift
    command: npm start
    
  mongodb:
    image: mongo:6
    container_name: secureshift-db
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: s223580955_db_user
      MONGO_INITDB_ROOT_PASSWORD: Sanjolika@20003
      MONGO_INITDB_DATABASE: secureshift
    volumes:
      - mongo-data:/data/db
      - ./app-backend/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    restart: unless-stopped
    networks:
      - secureshift
      

  frontend-employer:
    build:
      context: ./app-frontend/employer-panel
    container_name: secureshift-frontend-employer
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - secureshift
    command: npm start
      
volumes:
  mongo-data:

networks:
  secureshift:
